### ISSUE TITLE
Jumping locations in the notification bar

### ISSUE THREAD

**Issue by Tvangeste** [opto/nostalgy-xpi#136]
I am not sure if it is for me only, or is this a global problem, but it gets a bit annoying so here we go.
In my Thunderbird, the nostalgy's notification area is at the bottom right of the corner, there is an icon and a suggested destination for the selected email there.

As soon as I press 'S' though, the text box appears, but it appears at the bottom LEFT of the screen, thus creating this weird jumping issue, when some part of Nostalgy UI is at the bottom right, but some part of Nostalgy UI appears at the bottom left.

Can something be done in this regard, so that the Nostalgy UI stays on the same place?

Thank you!

**Comment by blerner** [comment]
In addition to this, when the text box appears, it's substantially _taller_ than the status bar was, and the elastic space that pushed the other text in the status bar (unread / total / Today pane) to the right corner seems to vanish also, leading to some very odd UI glitches:
![image](https://user-images.githubusercontent.com/918464/172903946-d3baf59c-ff9f-4c4b-a6dd-a0e3e257dedf.png)


(I'm on TB 91.9.1 / Ubuntu 20.04 / Nostalgy 3.4.2)

**Comment by mitar** [comment]
On Ubuntu 24.04 with Thunderbird 140.3.1esr, to me the nostalgy bar is also much higher than regular status bar, so it jumps up.

**Comment by mitar** [comment]
I solved this with [custom CSS](https://kb.mozillazine.org/UserChrome.css):

```css
@namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul");
@namespace html url("http://www.w3.org/1999/xhtml");

#me-help {
  display: none !important;
}

html|button#spacesToolbarReveal {
  order: -2;
}

#status-bar > hbox[insertbefore="status-privacy"] {
  order: -1;
}

html|input#nostalgy-folderbox {
  padding: 3px !important;
  border: 0 !important;
}
```

This makes nostalgy left aligned, and also height matches now the size of the status bar for me.
