### ISSUE TITLE
Bad experience with dark theme

### ISSUE THREAD

**Issue by ttamttam** [opto/nostalgy-xpi#177]
When (this is my default setting) I select Thunderbird dark theme:
— the Search++ button is not visible (maybe there is a way to have it's color inversed, depending on the theme?)
— in the key shortcuts table, every second line is unreadable

Many thanks for your work on this essential  addon!

**Comment by fnxweb** [comment]
I'd add that under dark mode (Linux) the Prefs window's Rules tab shows white-on-white text for every other (even) row.  This can sort of be worked around as the text goes red when the row is selected.

**Comment by DrBoym** [comment]
This problem still exists, making Nostalgy very hard to use with any dark scheme. See example from my screen with standard dark mode from TB. Should be an easy fix, right?
![Nostalgy status bar](https://user-images.githubusercontent.com/89902458/183586085-111e9f46-2405-423d-a975-23f69093a165.JPG)
?

**Comment by joreiff** [comment]
In case anyone is interested: The following CSS fixes the status bar issue shown by @DrBoym:
``` css
hbox.statusbar[insertbefore="unreadMessageCount"] {
    appearance: none !important;
}

image#me-help {
    filter: invert(1);
}
```
Simply add it to the `chrome/userChrome.css` file inside your profile folder and restart Thunderbird.
